apiVersion: v1
kind: Namespace
metadata:
  name: x4g4t
  labels:
    name: x4g4t
    app.kubernetes.io/name: x4g4t
    app.kubernetes.io/part-of: x4g4t-platform
    pod-security.kubernetes.io/enforce: baseline

