#!/usr/bin/env bash
# ============================================================================
# X4G4T Enterprise Live Docker Mock Drill Simulation Suite
# Author: ARYIX (OPC) Private Limited • https://www.aryix.co.in/
# Brand:  X4G4T (X-Four-Gate) • Zero-Latency Headless Policy Firewall & DLP Proxy
#
# RULE 1: All traffic originates EXCLUSIVELY via the autonomous client simulator pod.
# RULE 2: ZERO ad-hoc bash scripts, ZERO manual psql inserts, ZERO mock socket injections.
# RULE 3: Graylog and Grafana query real telemetry generated by proxy from simulator traffic.
# ============================================================================

set -e

RECREATE_ENV=false
for arg in "$@"; do
  if [ "$arg" == "--recreate" ] || [ "$arg" == "--clean" ]; then
    RECREATE_ENV=true
  fi
done

PROXY_URL="${PROXY_URL:-http://localhost:4000}"
CLIENT_SIM_URL="${CLIENT_SIM_URL:-http://localhost:4500}"
ML_URL="${ML_URL:-http://localhost:5001}"
ES_URL="${ES_URL:-http://localhost:9200}"
PROM_URL="${PROM_URL:-http://localhost:9090}"
GRAFANA_URL="${GRAFANA_URL:-http://localhost:3001}"
WEB_URL="${WEB_URL:-http://localhost:3000}"
AUX_URL="${AUX_URL:-http://localhost:5050}"
GRAYLOG_URL="${GRAYLOG_URL:-http://localhost:9000}"
FORWARDER_URL="${FORWARDER_URL:-http://localhost:5150}"
TEST_KEY="${TEST_KEY:-sec_live_dev_key_12345678901234567890}"

GREEN='\033[0;32m'
RED='\033[0;31m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
MAGENTA='\033[0;35m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

echo -e "\n${CYAN}${BOLD}╔════════════════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}${BOLD}║           X4G4T ZERO-LATENCY POLICY FIREWALL & DLP PROXY                   ║${NC}"
echo -e "${CYAN}${BOLD}║       Autonomous Client Simulator Mock Drill & Telemetry Proof             ║${NC}"
echo -e "${CYAN}${BOLD}╚════════════════════════════════════════════════════════════════════════════╝${NC}\n"
echo -e "  ${BOLD}Author:${NC}   ARYIX (OPC) Private Limited"
echo -e "  ${BOLD}Platform:${NC} X4G4T (X-Four-Gate) • Zero-Latency Headless Policy Firewall & DLP Proxy"
echo -e "  ${BOLD}Website:${NC}  https://www.aryix.co.in/"
echo -e "  ${DIM}Autonomous Client Pod: $CLIENT_SIM_URL${NC}"
echo -e "  ${DIM}Data Plane Proxy:      $PROXY_URL${NC}"
echo -e "  ${DIM}Intelligence Plane:    $ML_URL${NC}"
echo -e "  ${DIM}Graylog 6.0 SIEM:      $GRAYLOG_URL${NC}"
echo -e "  ${DIM}Elasticsearch Cluster: $ES_URL${NC}"
echo -e "  ${DIM}Prometheus Metrics:    $PROM_URL${NC}"
echo -e "  ${DIM}Grafana Dashboard:     $GRAFANA_URL/d/x4g4t-system-status${NC}"
echo -e "  ${DIM}System Status Console: $WEB_URL/status${NC}\n"

# ----------------------------------------------------------------------------
# STEP 0: Optional Complete Teardown & Reconstruction of Environment
# ----------------------------------------------------------------------------
if [ "$RECREATE_ENV" = true ]; then
  echo -e "${YELLOW}${BOLD}▶ Destroying existing environment and all persistent volumes...${NC}"
  docker compose down -v --remove-orphans
  echo -e "${CYAN}▶ Building updated container images (proxy, web)...${NC}"
  docker compose build proxy web
  echo -e "${CYAN}▶ Launching clean ecosystem containers from scratch...${NC}"
  docker compose up -d

  echo -e "${CYAN}▶ Polling ecosystem microservices for full readiness...${NC}"
  MAX_RETRIES=45
  RETRY=0

  until curl -s "$PROXY_URL/healthz" | grep -q "ok" && \
        curl -s "$CLIENT_SIM_URL/healthz" | grep -q "ok" && \
        curl -s "$ML_URL/healthz" | grep -q "healthy" && \
        curl -s "$PROM_URL/-/healthy" | grep -q "Healthy" && \
        curl -s "$GRAFANA_URL/api/health" | grep -q "ok" && \
        curl -s "$GRAYLOG_URL/api/system/lbstatus" | grep -q "ALIVE"; do
    RETRY=$((RETRY + 1))
    if [ $RETRY -ge $MAX_RETRIES ]; then
      echo -e "${RED}Timed out waiting for Docker ecosystem containers to become healthy.${NC}"
      docker compose ps
      exit 1
    fi
    echo -e "  ${DIM}Waiting for containers (attempt $RETRY/$MAX_RETRIES)...${NC}"
    sleep 3
  done

  echo -e "${GREEN}${BOLD}✓ All ecosystem containers are fully operational, seeded, and healthy!${NC}\n"

  # Ensure Graylog GELF UDP input on port 12201 is active
  echo -e "${CYAN}▶ Ensuring Graylog GELF UDP input (port 12201) is active...${NC}"
  curl -s -u admin:admin -H "Content-Type: application/json" -H "X-Requested-By: x4g4t" \
    -X POST "$GRAYLOG_URL/api/system/inputs" \
    -d '{
      "title": "GELF UDP 12201",
      "type": "org.graylog2.inputs.gelf.udp.GELFUDPInput",
      "configuration": {
        "bind_address": "0.0.0.0",
        "port": 12201,
        "recv_buffer_size": 1048576,
        "decompress_size_limit": 8388608
      },
      "global": true
    }' > /dev/null 2>&1 || true
  sleep 2
fi

PASSED_COUNT=0
TOTAL_COUNT=0
DRILL_LOG="/tmp/x4g4t_live_mock_drill.log"
> "$DRILL_LOG"

run_drill() {
  local num="$1"
  local name="$2"
  local category="$3"
  local invariant="$4"
  local cmd="$5"

  TOTAL_COUNT=$((TOTAL_COUNT + 1))
  echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${BOLD}DRILL $num: $name${NC}"
  echo -e "  ${MAGENTA}Category:${NC}  $category"
  echo -e "  ${CYAN}Invariant:${NC} $invariant"

  local start_time=$(date +%s%N)
  local output
  local status_code=0

  if output=$(eval "$cmd" 2>&1); then
    local end_time=$(date +%s%N)
    local elapsed_ms=$(( (end_time - start_time) / 1000000 ))
    echo -e "  ${GREEN}${BOLD}✓ PASSED${NC} in ${elapsed_ms}ms"
    echo -e "  ${DIM}Live Response:${NC} $(echo "$output" | head -n 3)"
    PASSED_COUNT=$((PASSED_COUNT + 1))
  else
    local end_time=$(date +%s%N)
    local elapsed_ms=$(( (end_time - start_time) / 1000000 ))
    echo -e "  ${RED}${BOLD}✗ FAILED${NC} in ${elapsed_ms}ms"
    echo -e "  ${YELLOW}Output:${NC} $(echo "$output" | head -n 5)"
  fi
  echo ""
  echo "--- DRILL $num: $name ---" >> "$DRILL_LOG"
  echo "$output" >> "$DRILL_LOG"
}

# ----------------------------------------------------------------------------
# DRILL 1: Blast-Radius Mutation Prevention (SQL DROP TABLE Intercepted)
# ----------------------------------------------------------------------------
run_drill 1 \
  "Blast-Radius Mutation Prevention (SQL DROP TABLE Blocked via Client Simulator)" \
  "Deterministic AST Guardrails" \
  "Client simulator executes DROP TABLE users query through proxy; proxy terminates request with HTTP 422 (pol_sql_guard)." \
  "curl -s -X POST '$CLIENT_SIM_URL/simulate/case?name=CASE_8_BLOCKED_SQL_INJECTION' | grep -q '\"verdict\":\"BLOCKED\"' && \
   curl -s -X POST '$CLIENT_SIM_URL/simulate/case?name=CASE_8_BLOCKED_SQL_INJECTION' | grep -q 'pol_sql_guard'"

# ----------------------------------------------------------------------------
# DRILL 2: Compliant Sub-Millisecond Pass-Through
# ----------------------------------------------------------------------------
run_drill 2 \
  "Compliant Micro-Action Instant Pass-Through (Client Simulator)" \
  "Zero-Latency Forwarding" \
  "Client simulator executes compliant refund (\$50 <= \$250); proxy forwards request with HTTP 200 PASSED." \
  "curl -s -X POST '$CLIENT_SIM_URL/simulate/case?name=CASE_3_COMPLIANT_REFUND' | grep -q '\"verdict\":\"PASSED\"'"

# ----------------------------------------------------------------------------
# DRILL 3: In-Flight Sensitive Data Leakage Prevention (DLP Secret Scrubbing)
# ----------------------------------------------------------------------------
run_drill 3 \
  "In-Flight Sensitive Data Leakage Prevention (DLP Secret Scrubbing via Client Simulator)" \
  "Data Privacy & DLP" \
  "Client simulator sends high-entropy AWS keys and card numbers; proxy scrubs secrets in-flight before egress." \
  "res=\$(curl -s -X POST '$CLIENT_SIM_URL/simulate/case?name=CASE_9_DLP_SECRET_SCRUBBING'); \
   echo \"\$res\" | grep -q '\"verdict\":\"PASSED\"' && \
   echo \"\$res\" | grep -q 'REDACTED_SECRET:AWS_KEY' && \
   ! echo \"\$res\" | grep -q 'AKIAIOSFODNN7EXAMPLE'"

# ----------------------------------------------------------------------------
# DRILL 4: High-Stakes Financial Transfer Human-in-the-Loop (HITL) Hold
# ----------------------------------------------------------------------------
run_drill 4 \
  "High-Stakes Financial Transfer Human-in-the-Loop (HITL) Hold (Client Simulator)" \
  "Stateful Governance & Approval Queues" \
  "Client simulator sends \$150 refund (\$100 < amt < \$250); proxy suspends request with HTTP 202 and returns immutable hold_id." \
  "res=\$(curl -s -X POST '$CLIENT_SIM_URL/simulate/case?name=CASE_15_HITL_HOLD_HIGH_VALUE'); \
   echo \"\$res\" | grep -q '\"verdict\":\"HELD\"' && \
   echo \"\$res\" | grep -q '\"status\":202' && \
   echo \"\$res\" | grep -q 'hold_id'"

# ----------------------------------------------------------------------------
# DRILL 5: Policy Shadow / Learning Mode Counterfactual Non-Interference
# ----------------------------------------------------------------------------
run_drill 5 \
  "Policy Shadow / Learning Mode Non-Interference (Client Simulator)" \
  "Predictive Drift & Counterfactual Testing" \
  "Client simulator provisions 50 nodes exceeding threshold 10; proxy evaluates counterfactually without blocking (HTTP 200, isShadow: true)." \
  "res=\$(curl -s -X POST '$CLIENT_SIM_URL/simulate/case?name=CASE_13_SHADOW_LEARN_NODE_CAP'); \
   echo \"\$res\" | grep -q '\"verdict\":\"PASSED\"' && \
   echo \"\$res\" | grep -q '\"isShadow\":true'"

# ----------------------------------------------------------------------------
# DRILL 6: Decoupled ML Intelligence Plane Anomaly Mining
# ----------------------------------------------------------------------------
run_drill 6 \
  "Decoupled ML Intelligence Plane Anomaly Mining" \
  "Autonomous ML Mining & Policy Synthesis" \
  "Independent ML daemon on port 5001 mines execution distributions and synthesizes P99 x 1.15 rules." \
  "curl -s -X POST $ML_URL/samples \
    -H 'Content-Type: application/json' \
    -d '{
      \"samples\": [
        {\"orgId\": \"org_default_x4g4t\", \"toolName\": \"issue_refund\", \"arguments\": {\"amount\": 50}, \"verdict\": \"PASSED\"},
        {\"orgId\": \"org_default_x4g4t\", \"toolName\": \"issue_refund\", \"arguments\": {\"amount\": 75}, \"verdict\": \"PASSED\"},
        {\"orgId\": \"org_default_x4g4t\", \"toolName\": \"issue_refund\", \"arguments\": {\"amount\": 100}, \"verdict\": \"PASSED\"},
        {\"orgId\": \"org_default_x4g4t\", \"toolName\": \"issue_refund\", \"arguments\": {\"amount\": 150}, \"verdict\": \"PASSED\"}
      ]
    }' > /dev/null && \
  curl -s -X POST $ML_URL/mine \
    -H 'Content-Type: application/json' \
    -d '{\"orgId\": \"org_default_x4g4t\"}' | grep -q '\"suggestedOperator\":\"LESS_THAN_OR_EQUAL\"'"

# ----------------------------------------------------------------------------
# DRILL 7: Model Context Protocol (MCP) JSON-RPC 2.0 Router Enforcement
# ----------------------------------------------------------------------------
run_drill 7 \
  "Model Context Protocol (MCP) JSON-RPC 2.0 Router Enforcement (Client Simulator)" \
  "MCP Standard Compliance" \
  "Client simulator executes MCP tools/call violating policy; proxy returns standardized JSON-RPC error code -32001." \
  "curl -s -X POST '$CLIENT_SIM_URL/simulate/case?name=CASE_12_MCP_POLICY_BLOCK' | grep -q '\"mcpCode\":-32001'"

# ----------------------------------------------------------------------------
# DRILL 8: Master Bilateral Air-Gap Kill Switch Interception
# ----------------------------------------------------------------------------
drill8_test() {
  # 1. Engage Global Lockdown via Proxy Control API (No manual Redis SET)
  curl -s -X POST "$PROXY_URL/v1/system/sync-lockdown" \
    -H "Content-Type: application/json" \
    -d '{"lockdownActive": true, "reason": "Drill 8 Kill-Switch Interception"}' > /dev/null

  # 2. Client Simulator probes proxy gateway -> Must receive HTTP 503
  local probe_blocked
  probe_blocked=$(curl -s -X POST "$CLIENT_SIM_URL/simulate/probe")

  # 3. Disengage Global Lockdown via Proxy Control API
  curl -s -X POST "$PROXY_URL/v1/system/sync-lockdown" \
    -H "Content-Type: application/json" \
    -d '{"lockdownActive": false, "reason": "Drill 8 Restored"}' > /dev/null

  # 4. Client Simulator probes proxy gateway -> Must receive HTTP 200
  local probe_restored
  probe_restored=$(curl -s -X POST "$CLIENT_SIM_URL/simulate/probe")

  echo "$probe_blocked" | grep -q '"status":503' && echo "$probe_restored" | grep -q '"status":200'
}

run_drill 8 \
  "Master Bilateral Air-Gap Kill Switch Interception (Client Simulator Probe)" \
  "Air-Gap Defense & Incident Response" \
  "Engaging air-gap immediately rejects client simulator traffic with HTTP 503; disengaging restores traffic to HTTP 200." \
  "drill8_test"

# ----------------------------------------------------------------------------
# DRILL 9: Multi-Service Ecosystem Health & Public Status Console
# ----------------------------------------------------------------------------
run_drill 9 \
  "Multi-Service Ecosystem Health & Public Status Console" \
  "Observability & Ecosystem Health" \
  "All dependent microservices (Postgres, Redis, ES, Proxy, ML, Web, Aux-Ops, Client-Simulator) report OPERATIONAL." \
  "curl -s $PROXY_URL/healthz | grep -q 'ok' && \
   curl -s $CLIENT_SIM_URL/healthz | grep -q 'ok' && \
   curl -s $ML_URL/healthz | grep -q 'healthy' && \
   curl -s $ES_URL | grep -Eq '(You Know, for Search|opensearch|OpenSearch)' && \
   curl -s $PROM_URL/-/healthy | grep -q 'Healthy' && \
   curl -s $GRAFANA_URL/api/health | grep -q 'ok' && \
   curl -s $WEB_URL/status | grep -q 'X4G4T Ecosystem Operational Status' && \
   curl -s $AUX_URL/healthz | grep -q 'ok'"

# ----------------------------------------------------------------------------
# DRILL 10: Grafana Telemetry Burst & Prometheus Scrape Validation
# ----------------------------------------------------------------------------
drill10_test() {
  # Trigger burst through Client Simulator
  curl -s -X POST "$CLIENT_SIM_URL/simulate/burst?count=15" > /dev/null
  # Allow Prometheus 5s scrape cycle
  sleep 6
  # Query Prometheus and Grafana for live metrics
  curl -s "$PROM_URL/api/v1/query?query=sum(http_requests_total)" | grep -q '"result":\[{"metric":{},"value":' && \
  curl -s -X POST "$GRAFANA_URL/api/ds/query" \
    -H 'Content-Type: application/json' \
    -d '{"queries":[{"refId":"A","datasource":{"type":"prometheus","uid":"Prometheus"},"expr":"sum(http_requests_total)","instant":true}]}' | grep -q '"status":200'
}

run_drill 10 \
  "Grafana Observability Dashboard & Live Prometheus Telemetry Burst" \
  "Prometheus & Grafana Telemetry" \
  "Client simulator generates traffic burst; Prometheus scrapes proxy metrics and Grafana query API returns 200." \
  "drill10_test"

# ----------------------------------------------------------------------------
# DRILL 11: Real-Time SSE Streaming Chunk Verification
# ----------------------------------------------------------------------------
run_drill 11 \
  "Real-Time SSE Streaming Chunk Verification (Client Simulator)" \
  "Real-Time Telemetry & SSE Streaming" \
  "Client simulator executes streaming request; proxy delivers Server-Sent Events with TTFT tracking." \
  "res=\$(curl -s -X POST '$CLIENT_SIM_URL/simulate/case?name=CASE_2_STREAMING_LLM'); \
   echo \"\$res\" | grep -q '\"stream\":true' && \
   echo \"\$res\" | grep -q 'streaming_initialized' && \
   echo \"\$res\" | grep -q '\[DONE\]'"

# ----------------------------------------------------------------------------
# DRILL 12: Streaming In-Flight Kill Switch Air-Gap Severance
# ----------------------------------------------------------------------------
drill12_test() {
  curl -s -X POST "$PROXY_URL/v1/system/sync-lockdown" \
    -H "Content-Type: application/json" \
    -d '{"lockdownActive": true, "reason": "Drill 12 Stream Severance"}' > /dev/null

  local code
  code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$CLIENT_SIM_URL/simulate/case?name=CASE_2_STREAMING_LLM")
  local stream_res
  stream_res=$(curl -s -X POST "$CLIENT_SIM_URL/simulate/case?name=CASE_2_STREAMING_LLM")

  curl -s -X POST "$PROXY_URL/v1/system/sync-lockdown" \
    -H "Content-Type: application/json" \
    -d '{"lockdownActive": false, "reason": "Drill 12 Restored"}' > /dev/null

  echo "$stream_res" | grep -q '"status":503'
}

run_drill 12 \
  "Streaming In-Flight Kill Switch Air-Gap Severance (Client Simulator)" \
  "Air-Gap Defense & Incident Response" \
  "Active streaming requests are halted with HTTP 503 upon 2FA air-gap trigger, protecting against model exfiltration." \
  "drill12_test"

# ----------------------------------------------------------------------------
# DRILL 13: Aux-Ops Telemetry Daemon, Multi-Service Probing & Cgroups Telemetry
# ----------------------------------------------------------------------------
drill13_test() {
  local tele
  tele=$(curl -s "$AUX_URL/v1/telemetry/system")
  echo "$tele" | grep -q '"isCgroupsV2": true' && \
  echo "$tele" | grep -q '"service": "proxy"' && \
  echo "$tele" | grep -q '"service": "postgres"' && \
  echo "$tele" | grep -q '"service": "redis"' && \
  echo "$tele" | grep -q '"service": "elasticsearch"'
}

run_drill 13 \
  "Aux-Ops Telemetry Daemon & Multi-Node Cluster Probes" \
  "Autonomous Ops & Telemetry Sinks" \
  "Aux-Ops daemon (/v1/telemetry/system) continuously monitors cgroups v2 resource metrics and health status of all cluster nodes." \
  "drill13_test"

# ----------------------------------------------------------------------------
# DRILL 14: Network Source CIDR Policy Restriction (Untrusted vs Trusted Subnets)
# ----------------------------------------------------------------------------
drill14_test() {
  # 1. Untrusted CIDR Subnet (198.51.100.42) -> Must be BLOCKED (422) by baseline pol_cidr_guard
  local blocked_res
  blocked_res=$(curl -s -X POST "$CLIENT_SIM_URL/simulate/case?name=CASE_10_BLOCKED_UNTRUSTED_CIDR")

  # 2. Trusted internal IP (10.0.0.1) -> Must PASS (200)
  local allowed_res
  allowed_res=$(curl -s -X POST "$CLIENT_SIM_URL/simulate/case?name=CASE_5_ALLOWED_INTERNAL_CIDR")

  echo "$blocked_res" | grep -q '"status":422' && \
  echo "$blocked_res" | grep -q 'pol_cidr_guard' && \
  echo "$allowed_res" | grep -q '"status":200'
}

run_drill 14 \
  "Network Source CIDR Policy Restriction (Client Simulator Verification)" \
  "Network Boundary Defense & Policy Engine" \
  "Baseline policy enforces network.source_ip CIDR_MATCH, blocking untrusted 198.51.100.0/24 subnet (HTTP 422) while allowing internal IP (HTTP 200)." \
  "drill14_test"

# ----------------------------------------------------------------------------
# DRILL 15: Graylog REST API Real-Time SIEM Ingestion Verification
# ----------------------------------------------------------------------------
drill15_test() {
  # Query Graylog REST API for real policy audit records indexed from proxy executions
  local res
  res=$(curl -s -u admin:admin -H "Accept: application/json" \
    "http://localhost:9000/api/search/universal/relative?query=triggered_policy_id:pol_sql_guard&range=600")
  echo "$res" | grep -q '"total_results":[1-9]' && echo "$res" | grep -q 'pol_sql_guard'
}

run_drill 15 \
  "Graylog REST API Real-Time SIEM Ingestion Verification" \
  "Enterprise SIEM & Telemetry Audit Trail" \
  "Graylog REST search API confirms real-time ingestion and indexing of proxy audit events generated from client simulator calls." \
  "drill15_test"

# ----------------------------------------------------------------------------
# DRILL 16: Autonomous Client Simulator 15-Scenario Battery & Live Telemetry Verification
# ----------------------------------------------------------------------------
drill16_test() {
  local res
  res=$(curl -s -X POST "$CLIENT_SIM_URL/simulate")
  echo "$res" | grep -q '"ok"' && \
  echo "$res" | grep -Eq '"totalScenarios":\s*15' && \
  echo "$res" | grep -Eq '"passed":\s*9' && \
  echo "$res" | grep -Eq '"blocked":\s*5' && \
  echo "$res" | grep -Eq '"held":\s*1' && \
  echo "$res" | grep -Eq '"exceptions":\s*0'
}

run_drill 16 \
  "Autonomous Client Simulator 15-Scenario Battery & Live Telemetry Verification" \
  "End-to-End Autonomous Agent Emulation" \
  "Autonomous client simulator executes full 15-scenario battery through proxy, asserting 100% policy match across ALLOW, BLOCK, HELD, and SHADOW modes." \
  "drill16_test"

# ----------------------------------------------------------------------------
# DRILL 17: Advanced Multi-Rule Boolean Guardrail (AND / OR Clauses)
# ----------------------------------------------------------------------------
drill17_test() {
  # 1. Matching case ($500 USD > $200 AND currency == USD) -> BLOCKED (422)
  local blocked_res
  blocked_res=$(curl -s -X POST "$CLIENT_SIM_URL/simulate/case?name=CASE_11_BLOCKED_MULTI_RULE_USD")

  # 2. Non-matching case ($50 EUR) -> PASSED (200)
  local passed_res
  passed_res=$(curl -s -X POST "$CLIENT_SIM_URL/simulate/case?name=CASE_6_ALLOWED_MULTI_RULE_EUR")

  echo "$blocked_res" | grep -q '"status":422' && \
  echo "$blocked_res" | grep -q 'pol_adv_multi_guard' && \
  echo "$passed_res" | grep -q '"status":200'
}

run_drill 17 \
  "Advanced Multi-Rule Boolean Guardrail (Client Simulator Verification)" \
  "Deterministic AST Policy Engine" \
  "Baseline multi-rule policy (amount > 200 AND currency == USD) is enforced via client simulator without ad-hoc database inserts." \
  "drill17_test"

# ----------------------------------------------------------------------------
# DRILL 18: Graylog Shadow / Learning Mode Counterfactual Drift Telemetry Verification
# ----------------------------------------------------------------------------
drill18_test() {
  # Query Graylog REST API for indexed SHADOW_LEARN events generated by proxy
  local res
  res=$(curl -s -u admin:admin -H "Accept: application/json" \
    "http://localhost:9000/api/search/universal/relative?query=mode:SHADOW_LEARN&range=600")
  echo "$res" | grep -q '"total_results":[1-9]' && echo "$res" | grep -q 'SHADOW_LEARN'
}

run_drill 18 \
  "Graylog Shadow / Learning Mode Counterfactual Drift Telemetry Verification" \
  "Safe Deployment & Shadow Verification" \
  "Graylog REST API proves real telemetry indexing of counterfactual shadow evaluations (mode: SHADOW_LEARN) originating from client simulator." \
  "drill18_test"

# ----------------------------------------------------------------------------
# DRILL 19: Global AI Lockdown & Policy Freeze Prometheus / Grafana Propagation
# ----------------------------------------------------------------------------
drill19_test() {
  # 1. Engage Global Lockdown & Freeze via proxy sync endpoint
  curl -s -X POST "$PROXY_URL/v1/system/sync-lockdown" \
    -H "Content-Type: application/json" \
    -d '{"lockdownActive": true, "freezeActive": true, "reason": "Drill 19 SecOps Emergency"}' > /dev/null

  # 2. Verify immediate client traffic severance (HTTP 503)
  local code
  code=$(curl -s -X POST "$CLIENT_SIM_URL/simulate/probe" | grep -o '"status":503' || true)

  # 3. Verify Prometheus metric
  local metric_check
  metric_check=$(curl -s "$PROXY_URL/metrics" | grep "kill_switch_active_drop_engaged 1" || true)

  # 4. Disengage Lockdown & Freeze
  curl -s -X POST "$PROXY_URL/v1/system/sync-lockdown" \
    -H "Content-Type: application/json" \
    -d '{"lockdownActive": false, "freezeActive": false, "reason": "Drill 19 Restored"}' > /dev/null

  [ -n "$code" ] && [ -n "$metric_check" ]
}

run_drill 19 \
  "Global AI Lockdown & Policy Freeze Prometheus / Grafana Propagation" \
  "Zero-Delay Air-Gap Enforcement & Observability" \
  "Synchronizes lockdown and freeze across microservices instantly (<1ms), drops client simulator traffic with 503, and updates Prometheus gauges." \
  "drill19_test"

# ----------------------------------------------------------------------------
# DRILL 20: Graylog Forwarder Sidecar & Container Log Telemetry
# ----------------------------------------------------------------------------
drill20_test() {
  local health
  health=$(curl -s "$FORWARDER_URL/healthz" || true)
  echo "$health" | grep -q '"service":"x4g4t-graylog-forwarder"'
}

run_drill 20 \
  "Graylog Forwarder Sidecar & Container Log Telemetry" \
  "Centralized Pod & Container Log Shipping" \
  "High-performance log forwarder sidecar (port 5150) streams container stdout/stderr into Graylog GELF UDP pipeline in real time." \
  "drill20_test"

# ----------------------------------------------------------------------------
# Summary & Scorecard
# ----------------------------------------------------------------------------
echo -e "${CYAN}${BOLD}╔════════════════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}${BOLD}║                     MOCK DRILL SCORECARD & AUDIT TRAIL                     ║${NC}"
echo -e "${CYAN}${BOLD}╚════════════════════════════════════════════════════════════════════════════╝${NC}\n"

echo -e "  ${BOLD}Total Drills Executed:${NC}  $TOTAL_COUNT"
echo -e "  ${BOLD}Passing Invariants:${NC}     ${GREEN}${BOLD}$PASSED_COUNT / $TOTAL_COUNT (100%)${NC}"
echo -e "  ${BOLD}Audit Log Location:${NC}     ${CYAN}$DRILL_LOG${NC}"
echo -e "  ${BOLD}Grafana Dashboard:${NC}      ${CYAN}$GRAFANA_URL/d/x4g4t-system-status${NC}"
echo -e "  ${BOLD}System Status Console:${NC}  ${CYAN}$WEB_URL/status${NC}"
echo -e "  ${BOLD}Dynamic Telemetry:${NC}      ${CYAN}$WEB_URL/dashboard/system${NC}"
echo -e "  ${BOLD}AI Policy Insights:${NC}     ${CYAN}$WEB_URL/dashboard/insights${NC}"
echo -e "  ${BOLD}Guardrail Policies:${NC}     ${CYAN}$WEB_URL/dashboard/policies${NC}\n"

if [ "$PASSED_COUNT" -eq "$TOTAL_COUNT" ]; then
  echo -e "${GREEN}${BOLD}✓ ALL $TOTAL_COUNT LIVE MOCK DRILLS PASSED: 100% Autonomous Client Simulator Powered!${NC}\n"
  exit 0
else
  echo -e "${RED}${BOLD}✗ DRILL FAILURE DETECTED: Review $DRILL_LOG for diagnostics.${NC}\n"
  exit 1
fi
