global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "x4g4t-proxy"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["proxy:4000"]
        labels:
          environment: "production"
          service: "x4g4t-gateway"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

