global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "x4g4t-proxy"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["proxy:4000"]
        labels:
          environment: "production"
          service: "x4g4t-gateway"

  - job_name: "x4g4t-ml-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["ml-service:5001"]
        labels:
          environment: "production"
          service: "x4g4t-ml-service"

  - job_name: "x4g4t-aux-ops"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["aux-ops:5050"]
        labels:
          environment: "production"
          service: "x4g4t-aux-ops"

  - job_name: "cadvisor"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          environment: "production"
          service: "container-telemetry"

  - job_name: "x4g4t-web"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["web:3000"]
        labels:
          environment: "production"
          service: "x4g4t-web"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]



