apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: Prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    uid: Elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "x4g4t-logs-*"
    editable: true
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"
      interval: "Daily"
      logMessageField: "toolName"
      logLevelField: "verdict"

